# Generated by Django 5.0.2 on 2024-03-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysToRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_monday', models.BooleanField(default=False)),
                ('repeat_tuesday', models.BooleanField(default=False)),
                ('repeat_wednesday', models.BooleanField(default=False)),
                ('repeat_thursday', models.BooleanField(default=False)),
                ('repeat_friday', models.BooleanField(default=False)),
                ('repeat_saturday', models.BooleanField(default=False)),
                ('repeat_sunday', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quest')),
            ],
        ),
    ]
