# Generated by Django 4.2.10 on 2024-03-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_daystorepeat_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
