# Generated by Django 4.2.10 on 2024-03-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quest_date_created_alter_quest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='date_completed',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
