# Generated by Django 4.2.10 on 2024-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quest_completed_alter_quest_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='repeating',
            field=models.BooleanField(default=False),
        ),
    ]
