# Generated by Django 4.2.10 on 2024-03-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_quest_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='repeating',
        ),
    ]
