# Generated by Django 4.2.10 on 2024-03-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_quest_repeating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
