# Generated by Django 4.2.10 on 2024-03-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_quest_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='repeats_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_repeats_information', to='main.daystorepeat'),
        ),
    ]
