# Generated by Django 4.2.10 on 2024-03-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_quest_repeats_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='repeats_information',
        ),
    ]
