# Generated by Django 4.2.10 on 2024-03-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quest_repeats_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='repeats_information',
            field=models.JSONField(null=True),
        ),
    ]
