# Generated by Django 4.2.10 on 2024-03-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_quest_repeats_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='repeats_information',
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quest')),
            ],
        ),
    ]
