# Generated by Django 4.2.10 on 2024-03-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_quest_repeats_information_recurringschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringSchedule',
        ),
    ]
