# Generated by Django 4.2.10 on 2024-03-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_quest_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
